image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore dependencies
    init: |
      wget -O protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v3.15.8/protoc-3.15.8-linux-x86_64.zip
      unzip protoc.zip -d /workspace/local
      rm protoc.zip
      dotnet tool install --global dotnet-reportgenerator-globaltool
      dotnet tool install --global dotnet-outdated-tool
      dotnet restore
vscode:
  extensions:
    - muhammad-sammy.csharp
