version: "3.8"

services:
  server:
    image: cyclonedx/bom-repository-server
    build: .
    environment:
      - "REPO__DIRECTORY=/repo"
      - "ALLOWEDMETHODS__GET=true"
      - "ALLOWEDMETHODS__POST=true"
      - "ALLOWEDMETHODS__DELETE=true"
    ports:
      - 8000:8080
    volumes:
      - ./bomstorage:/repo
