# For details of what checks are run for PRs please refer below
name: Test CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  # Fail if there are any failed tests
  #
  # We support .NET 6.0 on Windows, Mac and Linux.
  #
  # To check for failing tests locally run `dotnet test`.
  test:
    name: Tests for .NET 6.0 on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.2.0

    - name: Set up .Net
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: '6.0'

    - name: Run tests
      run: |-
        dotnet restore
        dotnet test --nologo --no-restore --configuration Release --verbosity normal
