# For details of what checks are run for PRs please refer below
name: .NET Core CI

on: [pull_request, workflow_dispatch]

jobs:
  # Fail if there are any failed tests
  #
  # We support .NET 6.0 on Windows, Mac and Linux.
  #
  # To check for failing tests locally run `dotnet test`.
  test:
    name: Tests for .NET ${{ matrix.framework }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: '6.0'

    - name: Tests
      run: |
        dotnet restore
        dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov

    - name: Publish coverage report to coveralls.io   
      uses: coverallsapp/github-action@master   
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        path-to-lcov: tests/CycloneDX.BomRepoServer.Tests/TestResults/coverage.info