# For details of what checks are run for PRs please refer below
name: .NET Core CI

on: [pull_request, workflow_dispatch]

jobs:
  # Fail if there are any failed tests
  #
  # We support .NET 5.0 on Windows, Mac and Linux.
  #
  # To check for failing tests locally run `dotnet test`.
  test:
    name: Tests for .NET ${{ matrix.framework }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: '5.0.100-rc.2.20479.15'

    - name: Tests
      run: |
        dotnet restore
        dotnet test --framework net5.0
